export type AutoServiceSite = "global" | "china";

export const AUTOSERVICE_COPY = {
  global: {
    lang: "en",
    htmlLang: "en",
    siteHref: "/autoservice/global",
    demoSubject: "AutoService international demo",
    expertSubject: "AutoService international expert conversation",
    nav: [
      { label: "Product", href: "#product" },
      { label: "Channels", href: "#channels" },
      { label: "Integrations", href: "#integrations" },
      { label: "AI Engine", href: "#ai-engine" },
      { label: "Resources", href: "#resources" },
      { label: "Pricing", href: "#demo" },
    ],
    seo: {
      title: "AutoService | AI Agents for International After-Sales Support",
      description:
        "AutoService automates international after-sales support across voice, email, web chat, WhatsApp, SMS, social, in-app, and API channels with AI agents connected to global CRM and service systems.",
      ogTitle: "AutoService, AI Agents for International After-Sales Support",
      ogDescription: "Resolve international customer issues across global channels with AI agents that understand, reason, act, and improve.",
    },
    hero: {
      kicker: "AutoService International",
      title: "AI Agents for International After-Sales Support",
      lead:
        "Resolve customer issues across global channels with AI agents that understand questions, follow after-sales policies, connect to your CRM, and take action through your business systems.",
      loginCta: "Log in",
      primaryCta: "Book a demo",
      secondaryCta: "See how it works",
    },
    demoForm: {
      title: "Book an AutoService demo",
      intro: "Tell us who should receive the demo plan. The operations team will follow up from the admin console.",
      company: "Company",
      companyPlaceholder: "Your company name",
      contact: "Contact",
      contactPlaceholder: "Your name",
      mobile: "Phone",
      mobilePlaceholder: "+1 555 0100",
      email: "Email",
      emailPlaceholder: "name@company.com",
      role: "Role",
      rolePlaceholder: "Customer service lead",
      scenario: "Scenario",
      scenarioPlaceholder: "Channels, CRM, and after-sales workflow you want to automate",
      cancel: "Cancel",
      close: "Close",
      submit: "Submit request",
      submitting: "Submitting",
      successTitle: "Request submitted",
      success: "Thank you for your interest. We will contact you soon.",
      error: "Submission failed. Please try again.",
    },
    visual: {
      channelsLabel: "International channels",
      traceLabel: "AutoService agent trace",
      outcomeLabel: "Outcome",
      outcomeTitle: "Resolved automatically",
      outcomeCopy: "Escalated with full context when approval is required.",
    },
    channels: ["Voice", "Email", "Web chat", "WhatsApp", "SMS", "Messenger", "Instagram", "In-app", "Help center", "Mobile SDK", "API", "Custom channels"],
    traceSteps: [
      { label: "Intent", value: "Return eligibility" },
      { label: "CRM", value: "Customer matched" },
      { label: "Order", value: "Status retrieved" },
      { label: "Policy", value: "Warranty checked" },
      { label: "Action", value: "Handoff summary generated" },
    ],
    trustLabel: "Works with the global systems your teams already use",
    trustLogos: ["Salesforce", "HubSpot", "Dynamics 365", "Zendesk", "Freshdesk", "Intercom", "ServiceNow", "Shopify", "Stripe", "FedEx", "DHL", "Custom API"],
    problem: {
      kicker: "International service layer",
      title: "Global after-sales support is fragmented. Your AI agent should not be.",
      columns: [
        { title: "Customers arrive everywhere", copy: "Voice, email, web chat, WhatsApp, SMS, social, help centers, and apps." },
        { title: "Answers live everywhere", copy: "Policies, manuals, help centers, CRM notes, historical tickets, and product documentation." },
        { title: "Actions happen everywhere", copy: "Orders, logistics, billing, subscriptions, warranty, returns, and repair systems." },
      ],
      bridge: "AutoService connects the conversation, the knowledge, and the action layer for international support teams.",
    },
    flow: {
      kicker: "How it works",
      title: "From customer message to resolved issue, automatically.",
      intro: "Four operating modes carry a request from language to action, with human escalation when the risk or policy boundary requires it.",
      steps: [
        { step: "01", title: "Understand", copy: "Detect intent, sentiment, language, and customer context before the first reply.", example: "A delayed-shipment message becomes a structured service request." },
        { step: "02", title: "Reason", copy: "Apply policies, SOPs, eligibility rules, and exception logic across regions.", example: "The agent checks SLA, carrier status, warranty terms, and refund guardrails." },
        { step: "03", title: "Act", copy: "Retrieve data, create cases, update systems, and trigger approved workflows.", example: "It drafts a case, updates the customer, and prepares the next action." },
        { step: "04", title: "Improve", copy: "Test, monitor, learn from outcomes, and surface knowledge gaps.", example: "Repeated escalations become a workflow or policy coaching signal." },
      ],
    },
    workflows: {
      kicker: "International workflows",
      title: "Built for real post-purchase journeys",
      headers: ["Journey", "Knowledge", "System data", "Playbook", "Action", "Handoff"],
      rows: [
        ["Order status", "Delivery policy", "Order + carrier", "Status update", "Notify customer", "Lost package"],
        ["Shipping delay", "SLA policy", "Carrier scan", "Exception logic", "Create case", "Compensation"],
        ["Return eligibility", "Return policy", "Order status", "Eligibility rules", "Return request", "Refund approval"],
        ["Warranty check", "Warranty terms", "Serial number", "Coverage check", "Repair intake", "Exception claim"],
        ["Troubleshooting", "Manual + articles", "Product profile", "Guided diagnosis", "Next step guide", "High-risk defect"],
      ],
    },
    integrations: {
      kicker: "Global integrations",
      title: "Connect AutoService to your CRM and service stack",
      intro: "No migration required. AutoService works as the AI service layer above the systems international teams already trust.",
      hubTitle: "AutoService",
      hubSubtitle: "AI service layer",
      groups: [
        { name: "CRM", items: ["Salesforce", "HubSpot", "Dynamics 365", "Custom CRM"], capability: "Read customer history, match accounts, and write service context back to the record." },
        { name: "Helpdesk", items: ["Zendesk", "Freshdesk", "Intercom", "ServiceNow"], capability: "Create cases, classify requests, route exceptions, and attach the AI trace." },
        { name: "Commerce", items: ["Shopify", "BigCommerce", "WooCommerce"], capability: "Check orders, returns, delivery promises, product status, and post-purchase rules." },
        { name: "Payments", items: ["Stripe", "Chargebee", "Recurly"], capability: "Pre-check subscription, refund, renewal, and billing context before escalation." },
        { name: "Logistics", items: ["FedEx", "UPS", "DHL", "ShipStation"], capability: "Read carrier status, detect delay patterns, and decide when humans need to step in." },
        { name: "Knowledge", items: ["Confluence", "Contentful", "Notion", "PDFs"], capability: "Ground answers in policies, manuals, articles, and historical resolution patterns." },
      ],
    },
    playbook: {
      kicker: "Agentic playbooks",
      title: "Turn after-sales SOPs into AI-executable playbooks",
      copy: "AutoService follows your policies step by step, asks for missing information, checks eligibility, and executes approved workflows only within the guardrails you define.",
      label: "Return Eligibility Playbook",
      rules: ["IF order delivered within 30 days", "AND product category is returnable", "AND warranty status is valid", "THEN provide return instructions", "ELSE explain exception and escalate"],
      outputLabel: "Agent output",
      outputTitle: "Customer is eligible for return.",
      outputCopy: "Order delivered 12 days ago. Product category allows returns. Next step: generate return label request.",
    },
    handoff: {
      kicker: "Human handoff",
      title: "When humans step in, they get the whole story.",
      reasonLabel: "Reason for escalation",
      reason: "Refund requires approval",
      fields: [
        { label: "Customer", value: "Maria Lopez" },
        { label: "Channels", value: "WhatsApp, Email, Web chat, Voice, SMS, Instagram, In-app, API" },
        { label: "Issue", value: "Delayed shipment, refund requested" },
        { label: "Checked", value: "CRM profile, order #A10291, carrier status, refund policy" },
        { label: "AI recommendation", value: "Approve refund review, carrier missed delivery SLA" },
        { label: "Risk", value: "Medium" },
      ],
    },
    engine: {
      kicker: "AI Engine",
      title: "AI that understands, reasons, acts, and improves",
      intro: "Each response is assembled from a traceable pipeline, not a loose chatbot turn.",
      labels: ["Input", "Operation", "Output"],
      steps: [
        ["Refine request", "Raw customer message", "Normalize language, detect intent, extract entities.", "Structured service request"],
        ["Retrieve knowledge", "Intent + entities", "Find policies, manuals, articles, and prior ticket patterns.", "Grounded source set"],
        ["Read context", "Customer + order ids", "Pull CRM, order, shipment, warranty, subscription, and ticket data.", "Business context packet"],
        ["Execute playbook", "Policy + context", "Follow after-sales SOPs and determine allowed actions.", "Approved next action"],
        ["Validate risk", "Draft action", "Check confidence, source coverage, policy fit, and escalation rules.", "Safe response or handoff"],
        ["Learn outcome", "Resolution result", "Surface knowledge gaps, failed workflows, and coaching suggestions.", "Improvement signal"],
      ],
    },
    evidence: {
      kicker: "Test, monitor, optimize",
      title: "Launch with confidence. Improve with evidence.",
      cards: [
        ["Resolution", "73%", "Automated cases resolved with source coverage"],
        ["Escalation", "18%", "Human handoff with full context and AI recommendation"],
        ["Knowledge gaps", "24", "Missing articles, weak policies, repeated exception patterns"],
      ],
    },
    security: {
      kicker: "Security and governance",
      title: "Enterprise control for AI service operations",
      copy: "AutoService is designed for controlled operations: permissions, approvals, auditability, and escalation rules stay visible as agents work across your systems.",
      items: ["Role-based access", "Tool permissions", "Action approvals", "Audit trails", "PII redaction", "Source-grounded responses", "Human escalation rules", "Model and workflow monitoring"],
    },
    finalCta: {
      kicker: "Start focused",
      title: "Turn international after-sales support into an AI-powered service engine.",
      copy: "Start with one workflow. Connect one CRM. Automate your first after-sales resolution in weeks, not quarters.",
      primary: "Book a demo",
      secondary: "Talk to an expert",
    },
  },
  china: {
    lang: "zh",
    htmlLang: "zh-CN",
    siteHref: "/autoservice/cn",
    demoSubject: "AutoService 演示预约",
    expertSubject: "AutoService 专家沟通",
    nav: [
      { label: "产品", href: "#product" },
      { label: "渠道", href: "#channels" },
      { label: "集成", href: "#integrations" },
      { label: "AI 引擎", href: "#ai-engine" },
      { label: "资源", href: "#resources" },
      { label: "方案", href: "#demo" },
    ],
    seo: {
      title: "AutoService | 售后服务 AI Agent",
      description: "AutoService 连接企业微信、钉钉、飞书、微信客服、公众号、小程序、电话、短信和业务系统，自动化售后咨询、工单、订单、物流、质保和人工接管。",
      ogTitle: "AutoService，售后服务 AI Agent",
      ogDescription: "连接企微、钉钉、飞书、CRM、工单、电商、物流和知识库，让售后 Agent 在业务系统中完成闭环。",
    },
    hero: {
      kicker: "AutoService",
      title: "售后服务 AI Agent",
      lead: "把企业微信、钉钉、飞书、微信客服、小程序、电话和短信里的售后请求接入同一个 AI 服务层，连接 CRM、工单、订单、物流、质保和知识库，按企业规则自动处理并转人工。",
      loginCta: "登录",
      primaryCta: "预约演示",
      secondaryCta: "了解流程",
    },
    demoForm: {
      title: "预约 AutoService 演示",
      intro: "留下基本信息后，运营管理后台会生成一条预约记录，团队会按场景跟进。",
      company: "公司名称",
      companyPlaceholder: "请输入公司名称",
      contact: "联系人",
      contactPlaceholder: "请输入联系人姓名",
      mobile: "联系电话",
      mobilePlaceholder: "请输入手机号或联系电话",
      email: "邮箱",
      emailPlaceholder: "name@company.com",
      role: "职位",
      rolePlaceholder: "售后负责人 / 运营负责人",
      scenario: "关注场景",
      scenarioPlaceholder: "例如：企微售后、工单流转、订单物流查询、人工接管",
      cancel: "取消",
      close: "关闭",
      submit: "提交预约",
      submitting: "提交中",
      successTitle: "预约提交成功",
      success: "感谢您的关注，我们会尽快与您取得联系",
      error: "提交失败，请稍后重试。",
    },
    visual: {
      channelsLabel: "接入渠道",
      traceLabel: "AutoService Agent 链路",
      outcomeLabel: "处理结果",
      outcomeTitle: "自动处理",
      outcomeCopy: "需要审批、赔付或异常判断时，携带完整上下文转交人工。",
    },
    channels: ["企业微信", "微信客服", "微信公众号", "微信小程序", "钉钉", "飞书", "电话", "短信", "网页客服", "App 内客服", "服务 API", "自有渠道"],
    traceSteps: [
      { label: "意图", value: "退换货咨询" },
      { label: "客户", value: "客户档案已匹配" },
      { label: "订单", value: "订单状态已读取" },
      { label: "规则", value: "售后政策已校验" },
      { label: "动作", value: "工单与转人工摘要已生成" },
    ],
    trustLabel: "连接团队已经在使用的系统",
    trustLogos: ["企业微信", "钉钉", "飞书", "CloudCC CRM", "Udesk", "顺丰", "自有 API"],
    problem: {
      kicker: "服务层",
      title: "售后被渠道、系统和流程切开，AI Agent 需要把它们重新连起来。",
      columns: [
        { title: "客户从多个渠道进入", copy: "企业微信、微信客服、公众号、小程序、钉钉、飞书、电话、短信和 App 内客服。" },
        { title: "答案分散在企业内部", copy: "售后政策、产品手册、服务话术、知识库、历史工单、客户备注和审批规则。" },
        { title: "动作发生在业务系统", copy: "CRM、工单、订单、仓储、物流、质保、发票、合同和内部审批流。" },
      ],
      bridge: "AutoService 把客户渠道、企业知识和业务动作连成一个可审计的售后闭环。",
    },
    flow: {
      kicker: "工作方式",
      title: "从客户消息到售后处理，自动完成关键步骤。",
      intro: "四个运行模式把客户消息转成可审计动作，并在赔付、审批、投诉或政策边界需要时转人工。",
      steps: [
        { step: "01", title: "理解", copy: "识别客户意图、情绪、渠道来源、手机号、订单号和会员身份。", example: "一条企业微信里的物流催办会被转成结构化售后请求。" },
        { step: "02", title: "推理", copy: "应用售后政策、SOP、区域服务规则、质保条款和审批条件。", example: "Agent 会检查发货时效、顺丰轨迹、赔付边界和升级条件。" },
        { step: "03", title: "执行", copy: "读取客户、订单、物流、工单和质保数据，创建工单并触发已授权流程。", example: "自动补充工单字段，生成客户回复，并准备人工审批材料。" },
        { step: "04", title: "优化", copy: "沉淀高频问题、知识缺口、异常流程和人工接管原因。", example: "重复升级的问题会成为知识库、流程或质检优化信号。" },
      ],
    },
    workflows: {
      kicker: "售后流程",
      title: "围绕购买后旅程设计",
      headers: ["旅程", "知识", "系统数据", "Playbook", "动作", "转人工"],
      rows: [
        ["订单催办", "发货时效规则", "订单 + 物流轨迹", "状态解释", "同步客户", "超时投诉"],
        ["物流异常", "赔付与签收规则", "顺丰/菜鸟轨迹", "异常判断", "创建工单", "赔付审批"],
        ["退换货", "退换货政策", "订单 + 商品状态", "资格校验", "发起售后单", "退款审核"],
        ["质保维修", "质保条款", "序列号 + 购买记录", "保修判断", "维修受理", "争议处理"],
        ["客户投诉", "服务规范 + 话术", "客户档案 + 历史工单", "分级处理", "生成摘要", "主管接管"],
      ],
    },
    integrations: {
      kicker: "系统集成",
      title: "连接企微、钉钉、飞书和业务系统",
      intro: "无需迁移现有系统。AutoService 作为 AI 服务层运行在企业已经信任的渠道、CRM、工单、电商、物流和知识系统之上。",
      hubTitle: "AutoService",
      hubSubtitle: "AI 服务层",
      groups: [
        { name: "协同与客户触点", items: ["企业微信", "微信客服", "微信公众号", "微信小程序", "钉钉", "飞书"], capability: "接入客户沟通入口，识别外部联系人、会话来源、服务窗口和转人工边界。" },
        { name: "CRM", items: ["CloudCC CRM", "悟空 CRM", "自有 CRM"], capability: "读取客户档案、联系人、商机、合同、服务历史，并把售后上下文回写到客户记录。" },
        { name: "工单与客服", items: ["Udesk", "容联七陌", "网易七鱼", "美洽", "自建工单"], capability: "创建工单、分类诉求、同步 AI 链路、路由异常问题并保留人工处理上下文。" },
        { name: "电商与订单", items: ["微盟", "抖店", "天猫", "京东", "自有商城"], capability: "查询订单、商品、退换货、发货承诺、售后单和购买后规则。" },
        { name: "物流与履约", items: ["顺丰", "菜鸟", "京东物流", "中通", "圆通", "快递 100"], capability: "读取物流轨迹，识别签收、延误、拒收、异常派送和赔付触发条件。" },
        { name: "知识与审批", items: ["飞书文档", "钉钉文档", "语雀", "企业知识库", "OA 审批"], capability: "用内部政策、产品手册、服务话术和审批规则约束回答与动作。" },
      ],
    },
    playbook: {
      kicker: "Agentic Playbooks",
      title: "把售后 SOP 变成 AI 可执行流程",
      copy: "AutoService 按企业政策逐步处理，主动补齐订单号、手机号、商品、物流和售后原因，只在授权范围内执行查询、建单、摘要和审批前置动作。",
      label: "退换货资格 Playbook",
      rules: ["如果订单已签收且在售后期内", "且商品类目允许退换货", "且物流与质保信息匹配", "则生成售后单建议", "否则说明原因并转人工"],
      outputLabel: "Agent 输出",
      outputTitle: "客户符合换货受理条件。",
      outputCopy: "订单签收 7 天，商品类目支持换货，物流状态正常。下一步：创建售后工单并提交人工确认。",
    },
    handoff: {
      kicker: "人工接管",
      title: "转给人工前，先把情况说清楚。",
      reasonLabel: "升级原因",
      reason: "赔付需要审批",
      fields: [
        { label: "客户", value: "上海客户王女士" },
        { label: "渠道", value: "企业微信、微信客服、钉钉、飞书、电话、短信、App 内客服、服务 API" },
        { label: "问题", value: "物流延误，客户要求赔付" },
        { label: "已检查", value: "客户档案、订单 #CN10291、顺丰轨迹、售后政策、历史工单" },
        { label: "AI 建议", value: "建议进入赔付审核，物流时效已超过服务承诺" },
        { label: "风险", value: "中" },
      ],
    },
    engine: {
      kicker: "AI 引擎",
      title: "理解、推理、执行，并持续优化",
      intro: "每一次回复都来自可追踪的处理管线，而不是松散的一轮聊天。",
      labels: ["输入", "处理", "输出"],
      steps: [
        ["精炼请求", "客户原始消息", "规范语言、识别渠道、抽取手机号、订单号、商品和诉求。", "结构化售后请求"],
        ["检索知识", "意图 + 实体", "查找售后政策、服务手册、话术、审批规则和历史工单模式。", "有来源依据的知识集合"],
        ["读取上下文", "客户 + 订单 ID", "读取 CRM、订单、物流、质保、工单和会员数据。", "业务上下文包"],
        ["执行 Playbook", "政策 + 上下文", "遵循售后 SOP，判断可执行查询、建单、摘要或审批前置动作。", "获批的下一步动作"],
        ["校验风险", "草拟动作", "检查置信度、来源覆盖、政策匹配、投诉风险和人工接管规则。", "安全回复或转人工"],
        ["学习结果", "处理结果", "暴露知识缺口、流程断点、高频异常和质检建议。", "优化信号"],
      ],
    },
    evidence: {
      kicker: "测试、监控、优化",
      title: "上线后看得见效果，也知道哪里要改。",
      cards: [
        ["自动处理率", "68%", "有来源依据且无需人工首响的售后会话"],
        ["人工接管", "21%", "带完整上下文、建议动作和风险标记的升级"],
        ["知识缺口", "31", "缺失政策、弱流程、重复投诉和异常节点"],
      ],
    },
    security: {
      kicker: "安全与治理",
      title: "面向 AI 服务运营的企业级控制",
      copy: "AutoService 面向受控运营设计：成员权限、渠道权限、工具授权、审批规则、审计链路和客户数据脱敏在 Agent 跨系统工作时保持可见。",
      items: ["组织与成员权限", "渠道与工具授权", "高风险动作审批", "审计链路", "客户信息脱敏", "来源约束回答", "人工接管规则", "模型与流程监控"],
    },
    finalCta: {
      kicker: "从一个流程开始",
      title: "把售后服务变成 AI 驱动的服务闭环。",
      copy: "先接入一个渠道、一个 CRM 或工单系统、一个高频售后流程，在几周内跑通第一个可度量的自动处理闭环。",
      primary: "预约演示",
      secondary: "联系专家",
    },
  },
} as const;
